modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
Adds the Excavation enchantment: mine in a 3x3 (level I) or 5x5 (level II) area.
Works on all tools; pickaxes, axes, shovels, and hoes.
Each block drops its own correct loot.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.219,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
